### ISSUE TITLE
Add meta tags for rich snippets/social media

### ISSUE THREAD

**Issue by experimatt** [mplsjrdevs/mplsjrdevs#79]

**Comment by experimatt** [comment]
Use something like Twitter's Card Validator to preview what the meta tags will look like in twitter: https://cards-dev.twitter.com/validator

**Comment by FlannelBear** [comment]
I'm working on setting up a twitter card, and if we'd like an image to be included it requires a url.  Here is the description straight from the Twitter Dev documentation:

"URL of image to use in the card. Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported."

Do we have any publicly stored images to point the meta tag at? I think a good image would be the mplsjrdev logo.

**Comment by FlannelBear** [comment]
I'm currently working on implementing Open Graph and some Twitter specific meta tags, one of which requires a public url for am image to display on the card.  I was wondering if we have any images hosted anywhere that I could point the meta tags at?

**Comment by experimatt** [comment]
@FlannelBear I just added two 540x540px versions of the logo to the `/public` directory so you should be able to add relative references to them from the code. You'll probably want to use the `.jpg` version with the white background: https://github.com/mplsjrdevs/mplsjrdevs/blob/master/public/mplsjrdevs-logo-color.jpg

**Comment by experimatt** [comment]
Also, thank you for working on this! I really appreciate it :)

**Comment by FlannelBear** [comment]
I've tested the social card on twitter and it looks good except there is no image.  The "og:image" meta tag requires a full url with "http" or "https", and I'm unable to locate where the image is being stored on the deployed site.  Either we need to sort out the url within the domain where the logo is being stored, or move the logo into the media folder of the application, where we are currently adding images that become available on the website.

**Comment by experimatt** [comment]
This is done, nice work Josh!
