### ISSUE TITLE
Add Google Analytics tracking

### ISSUE THREAD

**Issue by experimatt** [mplsjrdevs/mplsjrdevs#8]
**UA number:** `UA-105372704-1`

**Tracking Code**

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-105372704-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-105372704-1');
</script>
```

**Comment by experimatt** [comment]
We may be able to pull in a react google analytics library instead of embedding the above code snippet

**Comment by jenessawhite** [comment]
@experimatt do you want to keep our GA tracking in a `.env` file?

**Comment by experimatt** [comment]
@jenessawhite does github even support that? I feel like we'll just use the same GA tag whether it's dev or production, so it doesn't matter to me. I'm perfectly fine hard-coding it

**Comment by jenessawhite** [comment]
Lol yes GH supports it, but you're right, I don't think we need to hide it.

**Comment by experimatt** [comment]
Hah, sorry I'm still in "Gitlab is better at everything" mode 😂
